# Generated by Django 3.2 on 2021-04-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20210430_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='white', max_length=90),
        ),
    ]
