# Generated by Django 3.2 on 2021-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_userprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sids',
            field=models.TextField(default=''),
        ),
    ]
