# Generated by Django 3.2 on 2021-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_cell_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2figure',
            name='on_board',
            field=models.BooleanField(default=False),
        ),
    ]
