# Generated by Django 3.2 on 2021-04-29 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_userprofile_sids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess.userprofile')),
            ],
        ),
    ]
