# Generated by Django 3.2 on 2021-04-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('image', models.ImageField(upload_to='figures')),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='white', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='User2Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.figure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.board')),
            ],
        ),
    ]
