# Generated by Django 3.2 on 2021-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_user2figure_on_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='stage',
            field=models.CharField(choices=[('setting', 'setting'), ('play', 'play')], default='setting', max_length=90),
        ),
    ]
