# Generated by Django 3.2 on 2021-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_user2figure_cellid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
