# Generated by Django 3.2 on 2021-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_auto_20210501_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='agressor_position_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='owner_position_done',
            field=models.BooleanField(default=False),
        ),
    ]
